---
- name: Install OS Packages
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - mesosphere-zookeeper

- name: Create zookeeper logs folder.
  file: path={{log_dir}} state=directory recurse=yes owner=root group=root
  tags: bootstrap

- name: Write myid file.
  template: src=myid.j2 dest={{data_dir}}/myid owner=root group=root
  tags: deploy
  notify:
    - Restart zookeeper

- name: Configure zookeeper
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg owner=root group=root
  tags: deploy
  notify:
    - Restart zookeeper

- name: Start zookeeper
  service: name=zookeeper state=started
  tags: deploy
